spring:
  datasource:
    username: root
    password: lqd31415926
    url: jdbc:mysql://mysql:3306/sbs_practice
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 200MB

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
