spring:
  datasource:
    username: root
    password: lqd31415926
    url: jdbc:mysql://127.0.0.1:3306/sbs_practice


# 开发环境配置
file:
  uploadPath: C:\\Users\\29443\\Documents\\GitHub\\practice\\practice-web\\static\\uploads\\files\\
  imageUploadPath: C:\\Users\\29443\\Documents\\GitHub\\practice\\practice-web\\static\\uploads\\images\\
  zipFileName: files.zip
  zipFileExtension: .zip
  teacher:
    filePath: C:\\Users\\29443\\Documents\\GitHub\\practice\\practice-web\\static\\uploads\\teacher\\files\\


minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  teacher-bucket: teacher
  student-bucket: user
