spring:
  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 200MB

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
