spring:
  datasource:
    username: root
    password: lqd31415926
    url: jdbc:mysql://mysql:3306/sbs_practice


# 生产环境配置
file:
  uploadPath: /root/uploads/files/
  imageUploadPath: /root/uploads/images/
  zipFileName: files.zip
  zipFileExtension: .zip
  teacher:
    filePath: /root/uploads/teacher/files/

minio:
  endpoint: http://172.100.48.84:9000
  accessKey: root
  secretKey: lqd31415926
  teacher-bucket: teacher
  student-bucket: user

